print("--------------------Joke Teller v0.0.1--------------------\
	\nLet me tell some jokes to you, press 'enter' to continue.")
print()

print("What do you get when you cross a snowman with a vampire?")
input()
print("FROSTBITE!")
print("What do dentists call an astronaut\'s cavity?")
input()
print("A black hole!")
print()
print("Knock knock......")
input()
print('Who is there?')
input()
print("Interrupting cow.")
input()
print("Interrupting cow wh", end = '')
print("-MOO!\n")
input("That's all, good")

